version: "3.7"
services:
    web:
        container_name: django-web
        build:
            context: app
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - ./app/.env
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:14.0-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
            PGDATA: /data/postgres
        volumes:
            - postgres-volume:/data/postgres
        ports:
            - "5432:5432"

volumes:
    postgres-volume: