version: "3.7"
services:

    postgres:
        container_name: postgres
        image: postgres:14.0-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
            PGDATA: /data/postgres
        volumes:
            - postgres-volume:/data/postgres
        ports:
            - "5432:5432"

volumes:
    postgres-volume: